kind: ConfigMap
apiVersion: v1
metadata:
  name: script
  namespace: {{ .Release.Namespace }}
data:
  download.txt: |
    # download
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: comfyui
  name: comfyui
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: comfyui
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        io.kompose.network/chrome-default: "true"
        io.kompose.service: comfyui
    spec:
      initContainers:
        - name: init-chmod-data
          image: 'docker.io/aboveos/busybox:latest'
          command:
            - sh
            - '-c'
            - |
              chown -R 1000:1000 /home/runner
          resources: {}
          volumeMounts:
            - name: appdata
              mountPath: /home/runner
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
          securityContext:
            runAsUser: 0
        - name: initcomfyuilocal
          image: 'docker.io/aboveos/yanwk-comfyui-boot:latest'
          command:
            - sh
            - '-c'
            - |-
              if [ ! -d "/home/runner" ] || [ -z "$(ls -A /home/runner)" ]; then
                  if [ -n "$(ls -A /cache)" ]; then
                      cp -a /cache/. /home/runner/
                  fi
              fi
          resources: {}
          volumeMounts:
            - name: appdata
              mountPath: /home/runner
            - name: cacheforstartup
              mountPath: /cache
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
        - name: initcomfyui
          image: 'docker.io/aboveos/yanwk-comfyui-boot:latest'
          command:
            - sh
            - '-c'
            - >-
              if [ ! -d /home/runner ]; then chmod u+x
              /home/scripts/download.sh; /home/scripts/download.sh; fi
          resources: {}
          volumeMounts:
            - name: appdata
              mountPath: /home/runner
            - name: volume-script
              readOnly: true
              mountPath: /home/scripts/download.txt
              subPath: download.txt
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
      containers:
      
        - env:
            - name: PGID
              value: "0"
            - name: PUID
              value: "0"
            - name: TZ
              value: Etc/UTC

          securityContext:
            runAsUser: 0
     
          image: "docker.io/aboveos/yanwk-comfyui-boot:latest"
          name: comfyui
          ports:

            - containerPort: 8188
                    
          resources: 
            requests:
              cpu: 250m
              memory: 2Gi
            limits:
              cpu: 4
              memory: 10Gi

          volumeMounts:
                      
            - mountPath: /home/runner
              name: appdata
            - name: modellibckp
              mountPath: /home/runner/ComfyUI/models/checkpoints
            - name: modelliblora
              mountPath: /home/runner/ComfyUI/models/loras
            - name: modellibvae
              mountPath: /home/runner/ComfyUI/models/vae
            - name: modellibhypernetworks
              mountPath: /home/runner/ComfyUI/models/hypernetworks
            - name: modellibembeddings
              mountPath: /home/runner/ComfyUI/models/embeddings
            - name: customnodes
              mountPath: /home/runner/ComfyUI/custom_nodes
            - name: volume-script
              readOnly: true
              mountPath: /home/scripts/download.txt
              subPath: download.txt

          imagePullPolicy: IfNotPresent
      restartPolicy: Always

      volumes:
        - name: appdata
          hostPath:
            type: DirectoryOrCreate
            path: {{ .Values.userspace.appData }}/comfyui
        - name: modellibckp
          hostPath:
            type: DirectoryOrCreate
            path: /ai/model/checkpoint
        - name: modelliblora
          hostPath:
            type: DirectoryOrCreate
            path: /ai/model/lora
        - name: modellibvae
          hostPath:
            type: DirectoryOrCreate
            path: /ai/model/vae
        - name: modellibembeddings
          hostPath:
            type: DirectoryOrCreate
            path: /ai/model/embeddings
        - name: modellibhypernetworks
          hostPath:
            type: DirectoryOrCreate
            path: /ai/model/hypernetworks
        - name: customnodes
          hostPath:
            path: /ai/comfyui/custom_nodes
            type: DirectoryOrCreate
        - name: cacheforstartup
          hostPath:
            path: /ai/comfyui/cacheforstartup
            type: DirectoryOrCreate
        - name: volume-script
          configMap:
            name: script
            defaultMode: 420
                      
status: {}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: comfyui
  name: comfyui
  namespace: {{ .Release.Namespace }}
spec:
  ports:

    - name: "8188"
      port: 8188
      targetPort: 8188
                    
  selector:
    io.kompose.service: comfyui
status:
  loadBalancer: {}
                  