---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: sdwebui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sdwebui
  template:
    metadata:
      labels:
        app: sdwebui
    spec:
      initContainers:
        - name: initcache
          image: 'docker.io/aboveos/busybox:latest'
          command:
            - sh
            - '-c'
            - 'if [ ! -d /data/config ]; then if [ "$(ls -A /cache)" ]; then cp -r /cache/.* /data/; fi fi'
          resources: {}
          volumeMounts:
            - name: cacheforstartup
              mountPath: /cache
            - name: sdmodel
              mountPath: /data
          imagePullPolicy: IfNotPresent
      containers:
      - name: sdwebui
        image: docker.io/aboveos/goolashe-automatic1111-sd-webui:latest
        resources:
          requests:
            cpu: 500m
            memory: 3Gi
          limits:
            cpu: 4000m
            memory: 24Gi
            nvidia.com/gpu: 1
        ports:
        - containerPort: 7860
        env:
        - name: CLI_ARGS
          value: "--allow-code --medvram --xformers --enable-insecure-extension-access --api"
        volumeMounts:
        - mountPath: /data
          name: sddata
        - name: modellibckp
          mountPath: /data/models/Stable-diffusion
        - name: modelliblora
          mountPath: /data/models/Lora
        - name: modellibvae
          mountPath: /data/models/VAE
        - name: modellibembeddings
          mountPath: /data/embeddings
        - name: modellibhypernetworks
          mountPath: /data/models/hypernetworks
        - name: extensions
          mountPath: /data/config/auto/extensions
        imagePullPolicy: IfNotPresent
      volumes:
      - name: sddata
        hostPath:
          type: DirectoryOrCreate
          path: {{ .Values.userspace.appData}}/sdwebui
      - name: modellibckp
        hostPath:
          type: DirectoryOrCreate
          path: {{ .Values.userspace.appData}}/modellib/checkpoint
      - name: modelliblora
        hostPath:
          type: DirectoryOrCreate
          path: {{ .Values.userspace.appData}}/modellib/lora
      - name: modellibvae
        hostPath:
          type: DirectoryOrCreate
          path: {{ .Values.userspace.appData}}/modellib/vae
      - name: modellibembeddings
        hostPath:
          type: DirectoryOrCreate
          path: {{ .Values.userspace.appData}}/modellib/embeddings
      - name: modellibhypernetworks
        hostPath:
          type: DirectoryOrCreate
          path: {{ .Values.userspace.appData}}/modellib/hypernetworks
      - name: cacheforstartup
        hostPath:
          path: {{ .Values.userspace.appData}}/sd/sdcachestartup
          type: DirectoryOrCreate
      - name: extensions
        hostPath:
          path: {{ .Values.userspace.appData}}/sd/extensions
          type: DirectoryOrCreate
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  selector:
    app: {{ .Release.Name }}
  ports:
    - protocol: TCP
      port: 7860
      targetPort: 7860
---
apiVersion: sys.bytetrade.io/v1alpha1
kind: ProviderRegistry
metadata:
  name: legacy-{{ .Release.Name }}
  namespace: user-system-{{ .Values.bfl.username }}
spec:
  dataType: legacy_sdwebui
  deployment: sdwebui
  description: sdwebui legacy api
  endpoint: sdwebui.{{ .Release.Namespace }}:7860
  group: api.sdwebui
  kind: provider
  namespace: {{ .Release.Namespace }}
  version: v2
  opApis:
  - name: All
    uri: /  
status:
  state: active